json/fermentation_step.json
json/recipes.json

Moving the fermentation steps into an array of it's own separate object.
Fermentation steps object provides details on various fermentation characteristics needed to properly represent a beer fermentation profile. 
Initial inclusions - 
Total time
Start/end temp
Start/end gravity
Start/end pH
Free Rise flag
Strings for documenting the type of vessel used and specific microorganism
Enum for main strains of microorganisms

Separate Fermentation Steps Object

---

json/measureable_units.json
tests/generic/fermentable.json
tests/generic/recipes.json
tests/real/CrystalMaltSpecialtyGrain.json
tests/real/FermentableRecord.json
tests/real/HopRecordWithAllFields.json
tests/real/HoppedExtract.json
tests/real/MashSingleStepInfusion.json
tests/real/MashTwoStepTemperature.json
tests/real/MedievalAle.json
tests/real/StyleBohemianPilsner.json
tests/real/StyleDryIrishStoutWithAllFields.json
tests/real/YeastWithMorePopularFields.json

Refactoring schema according to discussion Units #16

Units schema refactoring

---

docs/measureable_units.json.md
json/equipment.json
json/hops.json
json/measureable_units.json
tests/generic/equipment.json

Addresses #19 Please review @krutilin @superroma. 
Questions: Should additional properties be allowed to maximize compatibility between software, or disallowed to force the schema layout? Honestly I can't think of much else that would be _necessary_ to include in the equipment profile, although there's some stuff I would like to add like heat loss per hour.

Adding equipment.json

---

json/hops.json
tests/generic/recipes.json

Added generic test for the hop bill and removed duplicated hop forms descriptions.
Should fix #36

Add generic hop bill test

---

json/BeerXML.json
json/recipes.json

Fix that some descriptions are lost during conversion from xsd

---

json/style.json
tests/generic/styles.json
tests/real/StyleBohemianPilsner.json
tests/real/StyleDryIrishStoutWithAllFields.json
tests/styles/styleguide-2015.json
tests/tests.js

Extending style categorization according to https://github.com/beerjson/beerjson/issues/38

Bjcp styles

---

json/beer.json
tests/generic/cultures.json
tests/generic/equipment.json
tests/generic/fermentable.json
tests/generic/fermentation.json
tests/generic/hop_varieties.json
tests/generic/miscellaneous_ingredients.json
tests/generic/procedure.json
tests/generic/profiles.json
tests/generic/recipes.json
tests/generic/styles.json
tests/real/CorianderSpice.json
tests/real/CrystalMaltSpecialtyGrain.json
tests/real/FermentableRecord.json
tests/real/HopRecordWithAllFields.json
tests/real/HopWithRequiredFieldsOnly.json
tests/real/HoppedExtract.json
tests/real/IrishMoss.json
tests/real/MashSingleStepInfusion.json
tests/real/MashTwoStepTemperature.json
tests/real/MedievalAle.json
tests/real/SampleWaterProfile.json
tests/real/StyleBohemianPilsner.json
tests/real/StyleDryIrishStoutWithAllFields.json
tests/real/YeastWithMorePopularFields.json
tests/real/YeastWithRequiredFieldsOnly.json
tests/styles/styleguide-2015.json
tests/tests.js

Renamed BeerXML.json to Beer.JSON, updated tests accordingly

BeerXML to beerjson

---

json/fermentables.json
tests/generic/recipes.json

Make amount property required for the fermentable addition type
Fix #57

Make amount property required

---

js/beerxml-to-beerjson.js
json/recipe.json
tests/real/MedievalAle.json

Link to style.json in the recipe.json 

---

json/measureable_units.json
json/water.json
tests/real/SampleWaterProfile.json

Changed water properties from number value to ppm, and added the corresponding unit type of concentration with options of ppm, ppb, and mg/l. Updated tests accordingly..

Water profiles- Review changes

---

json/beer.json
json/culture.json
json/equipment.json
json/fermentable.json
json/fermentation.json
json/fermentation_step.json
json/hop.json
json/mash.json
json/mash_step.json
json/measureable_units.json
json/misc.json
json/recipe.json
json/style.json
json/water.json
package.json

And reformat all json stuff. 
Now it is possible to run prettier on precommit using `npm run precommit`.
Or it will run automatically after `npm i` with husky and git hooks after each commit.

Add prettier formatting rules

---

docs/mash_step.json.md
js/beerxml-to-beerjson.js
json/mash_step.json
tests/real/MashSingleStepInfusion.json
tests/real/MashTwoStepTemperature.json
tests/real/MedievalAle.json

Extend mash step to include sparging

---

js/beerxml-to-beerjson.js
json/measureable_units.json
json/style.json
tests/generic/fermentable.json
tests/generic/mash.json
tests/generic/recipes.json
tests/generic/styles.json
tests/real/BrettDosedKegsSaison.json
tests/real/CrystalMaltSpecialtyGrain.json
tests/real/FermentableRecord.json
tests/real/HopRecordWithAllFields.json
tests/real/HoppedExtract.json
tests/real/MedievalAle.json
tests/real/StyleBohemianPilsner.json
tests/real/StyleDryIrishStoutWithAllFields.json
tests/real/YeastWithMorePopularFields.json
tests/samples.test.js
tests/styles/ba_styleguide-2017.json
tests/styles/bjcp_styleguide-2015.json

Refactor measureable_units, I found that json validation does not work for some units, because of the unit type which is set incorrectly.
Also added units for percentage, carbonation and bitterness types to unify measurables structure.

Units refactoring

---

docs/fermentable.json.md
docs/measureable_units.json.md
docs/style.json.md
js/__snapshots__/json-schema-to-markdown.test.js.snap
js/beerxml-to-beerjson.js
json/fermentable.json
tests/converted/GenericOneHF.json
tests/converted/Kolsh.json
tests/converted/Londonpride.json
tests/converted/RRSummerBitter.json
tests/converted/punk-ipa-2010-current.json
tests/generic/recipes.json
tests/real/BrettDosedKegsSaison.json
tests/real/MedievalAle.json

Refactor fermentable.json and fix converter according to the #110

Refactor fermentable.json

---

docs/culture.json.md
docs/fermentable.json.md
docs/hop.json.md
docs/misc.json.md
docs/timing.json.md
js/__snapshots__/json-schema-to-markdown.test.js.snap
js/beerxml-to-beerjson.js
json/culture.json
json/fermentable.json
json/hop.json
json/misc.json
json/timing.json
tests/converted/GenericOneHF.json
tests/converted/Kolsh.json
tests/converted/Londonpride.json
tests/converted/RRSummerBitter.json
tests/converted/punk-ipa-2010-current.json
tests/real/BrettDosedKegsSaison.json
tests/real/IrishMoss.json
tests/real/MedievalAle.json
tests/samples.test.js

Extract timing type (maybe we should make it required)

Extract timing type

---

docs/hop.json.md
json/hop.json
tests/generic/recipes.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

We need information about hops timing to calculate recipe.

Make timing required

---

docs/culture.json.md
json/culture.json
tests/real/YeastWithMorePopularFields.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

to remove duplication of the attenuation field.

Suggestion to rename attenuation to the attenuation_range in the CultureInformation

---

docs/equipment.json.md
json/equipment.json
tests/generic/equipment.json
tests/real/EquipmentSet.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Attempt to refactor equipment type to store real equipment sets in the beerjson format. I added EquipmentItemType and made the assumption that root Equipment type is the set of the items.

Refactor equipment type

---

docs/recipe.json.md
json/recipe.json
tests/converted/GenericOneHF.json
tests/converted/Kolsh.json
tests/converted/Londonpride.json
tests/converted/RRSummerBitter.json
tests/converted/punk-ipa-2010-current.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Adds `apparent_attenuation` to recipe.js.  Updated docs and tests.  Solves #126

Add apparent_attenuation to recipe.js and updates docs & tests.  

---

docs/boil.json.md
json/boil.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

because generally it is calculated and depends on the current recipe.

Make pre_boil size not required

---

docs/culture.json.md
docs/fermentable.json.md
docs/hop.json.md
docs/misc.json.md
docs/water.json.md
js/__snapshots__/json-schema-to-markdown.test.js.snap
js/beerxml-to-beerjson.js
json/culture.json
json/fermentable.json
json/hop.json
json/misc.json
json/water.json
tests/converted/GenericOneHF.json
tests/converted/Kolsh.json
tests/converted/Londonpride.json
tests/converted/RRSummerBitter.json
tests/converted/punk-ipa-2010-current.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Per discussion on https://gitter.im/beerjson/beerjson

Replacing ambiguous references ('supplier'|'laboratory') by 'producer'

---

package-lock.json
yarn.lock

Fix npm and yarn audit security issues

Fix npm and yarn audit security issues

---

docs/culture.json.md
docs/fermentable.json.md
docs/hop.json.md
docs/mash.json.md
docs/mash_step.json.md
docs/measureable_units.json.md
docs/misc.json.md
docs/packaging.json.md
docs/packaging_vessel.json.md
docs/recipe.json.md
docs/timing.json.md
js/__snapshots__/json-schema-to-markdown.test.js.snap
json/culture.json
json/fermentable.json
json/hop.json
json/mash.json
json/mash_step.json
json/measureable_units.json
json/misc.json
json/packaging.json
json/packaging_vessel.json
json/recipe.json
json/timing.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Added a description to any property that was not self defining and would need explanation for a new brewer.

Added descriptions for better documentation

---

docs/culture.json.md
json/culture.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

complete culture properties

---

docs/culture.json.md
docs/mash.json.md
js/beerxml-to-beerjson.js
json/mash.json
tests/converted/GenericOneHF.json
tests/converted/Kolsh.json
tests/converted/RRSummerBitter.json
tests/real/MashTwoStepTemperature.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

sparge_temperature and ph removed from mash. From SPARGE_TEMP in BeerXML is created mash_step 'sparge' with that temperature and default time value of 15 minutes.

Sparge to mash step

---

docs/fermentable.json.md
docs/hop.json.md
docs/misc.json.md
js/__snapshots__/json-schema-to-markdown.test.js.snap
json/fermentable.json
json/hop.json
json/misc.json
tests/converted/GenericOneHF.json
tests/converted/Kolsh.json
tests/converted/RRSummerBitter.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Ingredient Product Ids

---

README.md
docs/beer.json.md
docs/water.json.md
js/__snapshots__/json-schema-to-flow.test.js.snap
js/__snapshots__/json-schema-to-markdown.test.js.snap
json/beer.json
json/fermentable.json
json/water.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Added overview section to readme.md for significant/notable changes from the current BeerXML 1.0 schema, and 2.0 proposal.
Removed references to "regional" in water descriptions.
Added timing object to the beer.json file for inclusion in documentation.

Documentation

---

docs/fermentable.json.md
docs/measureable_units.json.md
json/measureable_units.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Add pkg to the UnitUnitType

---

tests/real/BrettDosedKegsSaison.json
tests/real/CheaterHops.json
tests/real/CrystalMaltSpecialtyGrain.json
tests/real/HopRecordWithAllFields.json
tests/real/HoppedExtract.json
tests/real/IrishMoss.json
tests/real/MedievalAle.json
tests/real/StyleDryIrishStoutWithAllFields.json
tests/real/YeastWithMorePopularFields.json
tests/real/YeastWithRequiredFieldsOnly.json

Updated the samples in the real folder as not all properties will get flagged as being invalid (old beerjson properties) when the tests run.
This is a known problem with json schema when combining subschemas in allof as the additionalProperties get ignored because it knows nothing about the properties in the subschemas.
See:
https://github.com/json-schema-org/understanding-json-schema/issues/34

updated real samples

---

README.md
docs/fermentable.json.md
docs/measureable_units.json.md
docs/water.json.md
js/__snapshots__/json-schema-to-markdown.test.js.snap
json/fermentable.json
json/measureable_units.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

#132 Created a ViscosityType for the Viscosity property otherwise just followed @pricelessbrewing  suggestions for the properties types

Added spec sheet properties for maltsters

---

.github/workflows/tests.yml
.travis.yml

Move CI tests to Github actions.

Create tests.yml on Github actions

---

docs/timing.json.md

pH timing refers to gravity instead of pH.

fix timing docs for pH

---

docs/mash_step.json.md
json/mash_step.json
tests/real/FirstWortHopAddition.json
tests/real/KettleSour.json
tests/real/MashDecoction.json
tests/real/MashTwoStepTemperatureWithSparge.json
tests/real/SourFruitedCopitch.json
tests/real/SourMash.json
tests/real/SpargeAcidification.json
tests/real/boil_whirlpool_chill.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Added souring examples, sparge acidification, more complex hop addition examples.
Fixed pH instead of ph in step properties for consistency all use ph.

More examples

---

package.json

Adds "types": "types/ts/beerjson.d.ts", to package json so typescript can find the d.ts by the package name.
Closes #182

Adds "types": "types/ts/beerjson.d.ts", to package json

---

js/beerxml-to-beerjson.js

Update xml to beerjson converter.

Update xml to beerjson converter

---

docs/fermentable.json.md
js/__snapshots__/json-schema-to-markdown.test.js.snap
json/fermentable.json
types/flow-typed/beerjson.js
types/ts/beerjson.d.ts

Kolbach Index as a Percentage Type #186

---

docs/beer.json.md
docs/fermentable.json.md
json/beer.json

See https://github.com/beerjson/beerjson/issues/198 and https://github.com/beerjson/beerjson/issues/203
(Meant to do the water one as a separate PR, but GitHub had other ideas!  All pretty small changes though.)

Fix typos in beer.json, ferementable.json file & doco
